// Generated by svg2scad_simplified.py
// Modules: one module per SVG element (named glyph_<id>)

module glyph_apostrophe() {
    union() {
        polygon(points = [
            [68.948, -32.462],
            [67.485, -52.158],
            [66.731, -52.409],
            [62.781, -52.409],
            [61.318, -32.713],
            [62.035, -32.462],
            [67.960, -32.462],
            [68.948, -32.462],
        ]);
    }
}

// End of file
